application: circleresearchinc
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /hello
  script: hello.app

- url: /hw2/.*
  script: signup.app

#- url: /blog
#  script: blog2.app
- url: /blog.*
  script: blog2.app

#- url: /flush
#  script: blog2.app
- url: /flush.*
  script: blog2.app

#- url: /welcome
#  script: welcome.html


- url: /.*
  script: blog.app 
#  script: play.html 

libraries:
- name: jinja2
  version: latest
#- name: webapp2
#  version: "2.5.1"
